### ISSUE TITLE
getNextPageUrl

### ISSUE THREAD

**Issue by faudard** [Kicer86/github_api#10]
Hi thanks for this repo! I have an issue when I want to get the nextpage I found in windows 10 qt I need to change this line : 

        const std::regex nextPageRegex(R"(^link\: <([^>]+)>; rel="next".*)");

to
        const std::regex nextPageRegex(R"(^Link\: <([^>]+)>; rel=\"next\".*)");
(adding \") with this modification I get the different page.

**Comment by Kicer86** [comment]
Hi

Sorry about late answer, I have missed notification. I'll take a closer look this weekend.

**Comment by Kicer86** [comment]
Please verify if it works now and reopen if you still have problems.
