### ISSUE TITLE
github_api_export.h not found

### ISSUE THREAD

**Issue by IarChep** [Kicer86/github_api#13]
It's looks like you forgot to add github_api_export.h(for example in github_api-qt). Because when I try to include it, it is just can not be found.

Also,it will be good if you part your project to Qt6.

**Comment by Kicer86** [comment]
This file is automatically generated during build process. If you want to use Qt6, just set GitHubAPI_UseQt6 cmake variable to TRUE as stated here https://github.com/Kicer86/github_api#how-to-use-it
