### ISSUE TITLE
How would you make a call like this with Authorization: Bearer <YOUR-TOKEN>?

### ISSUE THREAD

**Issue by AgronAerco** [Kicer86/github_api#14]
Hello,

How would you put the Bearer token when trying to call an API like this one?

curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/milestones/MILESTONE_NUMBER/labels

https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#list-labels-for-issues-in-a-milestone

**Comment by Kicer86** [comment]
So it seems there are some changes in Github API which I'll have to include.

**Comment by Kicer86** [comment]
When calling `connect()` method of API, you can provide token.

Take a look inti examples, you can find there line like this:
`GitHub::Request request(github.connect());`

Just replace it with:
`GitHub::Request request(github.connect("ghp_XYZ...ABC"));`

@AgronAerco Is it what you need?

**Comment by AgronAerco** [comment]
OK, that could work.
Thank you so much.


Initially, I wanted to make use of
https://github.com/Kicer86/github_api/blob/f5abb5794d539254bab94574265fff284f166f5b/src/qt_backend/connection.cpp#L81

.. which uses a hardcoded term 'token'. Maybe we should have 'token_type' as well, to indicate if it is 'Basic' or 'Bearer' token type, and then associate the token content with it.
