### ISSUE TITLE
Sharing of this Github API 

### ISSUE THREAD

**Issue by aeonSolutions** [Kicer86/github_api#47]
Hi there @Kicer86 @kevinmukuna @Chaoses-Ib 
great work! 😍

I'm sharing your project on my own C++ project for the Github API
https://github.com/aeonSolutions/AeonLabs-GitHub-API-C-library

👍

**Comment by Kicer86** [comment]
Thank you for appreciation and good luck with your project

**Comment by aeonSolutions** [comment]
The same goes for you! 🙏💯
